/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ImpactsRouteImport } from './routes/impacts'
import { Route as JournalRouteImport } from './routes/journal'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as BriefingIndexRouteImport } from './routes/briefing.index'
import { Route as BriefingPortfolioRouteImport } from './routes/briefing.portfolio'
import { Route as MarketsIndexRouteImport } from './routes/markets.index'
import { Route as MarketsSymbolRouteImport } from './routes/markets.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactsRoute = ImpactsRouteImport.update({
  id: '/impacts',
  path: '/impacts',
  getParentRoute: () => rootRouteImport,
} as any)
const JournalRoute = JournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingIndexRoute = BriefingIndexRouteImport.update({
  id: '/briefing/',
  path: '/briefing/',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingPortfolioRoute = BriefingPortfolioRouteImport.update({
  id: '/briefing/portfolio',
  path: '/briefing/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsIndexRoute = MarketsIndexRouteImport.update({
  id: '/markets/',
  path: '/markets/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsSymbolRoute = MarketsSymbolRouteImport.update({
  id: '/markets/$symbol',
  path: '/markets/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/impacts': typeof ImpactsRoute
  '/journal': typeof JournalRoute
  '/research': typeof ResearchRoute
  '/briefing/portfolio': typeof BriefingPortfolioRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/briefing/': typeof BriefingIndexRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/impacts': typeof ImpactsRoute
  '/journal': typeof JournalRoute
  '/research': typeof ResearchRoute
  '/briefing/portfolio': typeof BriefingPortfolioRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/briefing': typeof BriefingIndexRoute
  '/markets': typeof MarketsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRoute
  '/auth': typeof AuthRoute
  '/impacts': typeof ImpactsRoute
  '/journal': typeof JournalRoute
  '/research': typeof ResearchRoute
  '/briefing/portfolio': typeof BriefingPortfolioRoute
  '/markets/$symbol': typeof MarketsSymbolRoute
  '/briefing/': typeof BriefingIndexRoute
  '/markets/': typeof MarketsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/auth'
    | '/impacts'
    | '/journal'
    | '/research'
    | '/briefing/portfolio'
    | '/markets/$symbol'
    | '/briefing/'
    | '/markets/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accounts'
    | '/auth'
    | '/impacts'
    | '/journal'
    | '/research'
    | '/briefing/portfolio'
    | '/markets/$symbol'
    | '/briefing'
    | '/markets'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/auth'
    | '/impacts'
    | '/journal'
    | '/research'
    | '/briefing/portfolio'
    | '/markets/$symbol'
    | '/briefing/'
    | '/markets/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRoute
  AuthRoute: typeof AuthRoute
  ImpactsRoute: typeof ImpactsRoute
  JournalRoute: typeof JournalRoute
  ResearchRoute: typeof ResearchRoute
  BriefingPortfolioRoute: typeof BriefingPortfolioRoute
  MarketsSymbolRoute: typeof MarketsSymbolRoute
  BriefingIndexRoute: typeof BriefingIndexRoute
  MarketsIndexRoute: typeof MarketsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impacts': {
      id: '/impacts'
      path: '/impacts'
      fullPath: '/impacts'
      preLoaderRoute: typeof ImpactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/journal': {
      id: '/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof JournalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/': {
      id: '/briefing/'
      path: '/briefing'
      fullPath: '/briefing/'
      preLoaderRoute: typeof BriefingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/portfolio': {
      id: '/briefing/portfolio'
      path: '/briefing/portfolio'
      fullPath: '/briefing/portfolio'
      preLoaderRoute: typeof BriefingPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/': {
      id: '/markets/'
      path: '/markets'
      fullPath: '/markets/'
      preLoaderRoute: typeof MarketsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets/$symbol': {
      id: '/markets/$symbol'
      path: '/markets/$symbol'
      fullPath: '/markets/$symbol'
      preLoaderRoute: typeof MarketsSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRoute,
  AuthRoute: AuthRoute,
  ImpactsRoute: ImpactsRoute,
  JournalRoute: JournalRoute,
  ResearchRoute: ResearchRoute,
  BriefingPortfolioRoute: BriefingPortfolioRoute,
  MarketsSymbolRoute: MarketsSymbolRoute,
  BriefingIndexRoute: BriefingIndexRoute,
  MarketsIndexRoute: MarketsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
